import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Float, Stars, useTexture } from "@react-three/drei";
import { Component, Suspense, useEffect, useMemo, useRef, type ReactNode } from "react";
import * as THREE from "three";
import { useExperienceStore } from "../store/experienceStore";

type CameraPoint={position:[number,number,number];target:[number,number,number]};
const cameraPath:CameraPoint[]=[];
const chapterIndexes:number[]=[];
type OrbitRange={start:number;end:number;center:[number,number,number];radius:number;height:number};
const orbitRanges:OrbitRange[]=[];
const beginChapter=()=>chapterIndexes.push(cameraPath.length);
const addPoint=(position:[number,number,number],target:[number,number,number])=>cameraPath.push({position,target});
const addTravel=(position:[number,number,number],target:[number,number,number],steps=24)=>{const start=cameraPath[cameraPath.length-1];if(!start){addPoint(position,target);return}for(let step=1;step<=steps;step+=1){const mix=step/steps;addPoint([THREE.MathUtils.lerp(start.position[0],position[0],mix),THREE.MathUtils.lerp(start.position[1],position[1],mix),THREE.MathUtils.lerp(start.position[2],position[2],mix)],[THREE.MathUtils.lerp(start.target[0],target[0],mix),THREE.MathUtils.lerp(start.target[1],target[1],mix),THREE.MathUtils.lerp(start.target[2],target[2],mix)])}};
const addOrbit=(center:[number,number,number],radius:number,height:number,steps=72)=>{const start=cameraPath.length;for(let step=0;step<=steps;step+=1){const angle=(step/steps)*Math.PI*2;addPoint([center[0]+Math.sin(angle)*radius,height,center[2]+Math.cos(angle)*radius],center)}orbitRanges.push({start,end:cameraPath.length-1,center,radius,height})};
beginChapter();addOrbit([0,0,0],12,2);
beginChapter();addTravel([7,1,9],[12,0,0]);addTravel([12,1.5,6],[12,0,0]);addOrbit([12,0,0],6,1.5);
beginChapter();addTravel([19,0,6],[27,0,0]);addTravel([25,1,5],[31,0,0]);addTravel([30,-1,4],[36,0,0]);addTravel([36,0,5],[42,0,0]);
beginChapter();addTravel([36,1,9],[42,0,0]);addOrbit([42,0,0],10,2.2);
beginChapter();addTravel([48,2,18],[58,0,0]);addOrbit([58,0,0],18,4);
beginChapter();addTravel([72,4,25],[86,0,0]);addOrbit([86,0,0],24,6);
beginChapter();addTravel([105,0,11],[113,0,0]);addTravel([116,0,8],[123,0,0]);addTravel([121,0,6],[128,0,0]);
beginChapter();addTravel([124,0,9],[128,0,0]);addTravel([128,2,7],[128,0,0]);addTravel([135,-1,6],[142,0,0]);
beginChapter();addTravel([139,0,12],[150,0,0]);addTravel([146,2,10],[150,0,0]);addTravel([151,0,8],[150,0,0]);addTravel([157,-1,7],[150,0,0]);
beginChapter();addTravel([163,0,7],[172,0,0]);addTravel([172,0,5],[181,0,0]);addTravel([182,0,4],[191,0,0]);addTravel([192,0,3],[202,0,0]);
export const CHAPTER_CUES=chapterIndexes.map(index=>index/(cameraPath.length-1));
const cameraPositions=cameraPath.map(point=>new THREE.Vector3(...point.position));
const cameraTargets=cameraPath.map(point=>new THREE.Vector3(...point.target));
function configure(texture: THREE.Texture, gl: THREE.WebGLRenderer, color=true) { useEffect(()=>{ if(color) texture.colorSpace=THREE.SRGBColorSpace; texture.anisotropy=gl.capabilities.getMaxAnisotropy(); texture.minFilter=THREE.LinearMipmapLinearFilter; texture.magFilter=THREE.LinearFilter; texture.needsUpdate=true },[texture,gl,color]) }

const atmosphereVertex="varying vec3 worldNormal;varying vec3 worldPosition;void main(){worldNormal=normalize(mat3(modelMatrix)*normal);worldPosition=(modelMatrix*vec4(position,1.0)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(worldPosition,1.0);}";
const atmosphereFragment="uniform vec3 glowColor;uniform float strength;varying vec3 worldNormal;varying vec3 worldPosition;void main(){vec3 viewDirection=normalize(cameraPosition-worldPosition);float rim=pow(1.0-max(dot(worldNormal,viewDirection),0.0),3.2);gl_FragColor=vec4(glowColor,rim*strength);}";
function Atmosphere({radius,color,strength=.72}:{radius:number;color:string;strength?:number}){return <mesh scale={1.035}><sphereGeometry args={[radius,56,56]}/><shaderMaterial vertexShader={atmosphereVertex} fragmentShader={atmosphereFragment} uniforms={{glowColor:{value:new THREE.Color(color)},strength:{value:strength}}} transparent depthWrite={false} side={THREE.BackSide} blending={THREE.AdditiveBlending}/></mesh>}
function CameraRig(){const {scrollProgress,reducedMotion,isPaused}=useExperienceStore();const renderedProgress=useRef(0),desiredPosition=useMemo(()=>new THREE.Vector3(),[]),desiredTarget=useMemo(()=>new THREE.Vector3(),[]);useFrame(({camera,clock},delta)=>{if(isPaused)return;renderedProgress.current=reducedMotion?scrollProgress:THREE.MathUtils.damp(renderedProgress.current,scrollProgress,7,Math.min(delta,.05));const pathProgress=renderedProgress.current*(cameraPath.length-1),index=Math.min(Math.floor(pathProgress),cameraPath.length-2),mix=pathProgress-index,orbit=orbitRanges.find(range=>pathProgress>=range.start&&pathProgress<=range.end);if(orbit){const local=(pathProgress-orbit.start)/(orbit.end-orbit.start),angle=local*Math.PI*2;desiredPosition.set(orbit.center[0]+Math.sin(angle)*orbit.radius,orbit.height,orbit.center[2]+Math.cos(angle)*orbit.radius);desiredTarget.set(...orbit.center)}else{desiredPosition.lerpVectors(cameraPositions[index],cameraPositions[index+1],mix);desiredTarget.lerpVectors(cameraTargets[index],cameraTargets[index+1],mix);if(!reducedMotion)desiredPosition.y+=Math.sin(clock.elapsedTime*.2)*.08}camera.position.copy(desiredPosition);camera.lookAt(desiredTarget)});return null}
type PlanetProps={position:[number,number,number];texture:string;size:number;atmosphere?:string};
function Planet({position,texture,size,atmosphere}:PlanetProps){const ref=useRef<THREE.Mesh>(null!);const map=useTexture(texture);const {gl}=useThree();configure(map,gl);useFrame((_,d)=>ref.current.rotation.y+=d*.025);return <group position={position}><mesh ref={ref}><sphereGeometry args={[size,80,80]}/><meshStandardMaterial map={map} roughness={.57} metalness={.04}/></mesh>{atmosphere&&<Atmosphere radius={size} color={atmosphere}/>}</group>}
function Earth(){const body=useRef<THREE.Mesh>(null!),cloud=useRef<THREE.Mesh>(null!);const [day,night,clouds]=useTexture(["/textures/planets/earth/earth-color-2k.jpg","/textures/planets/earth/earth-night-2k.jpg","/textures/planets/earth/earth-clouds-2k.jpg"]);const {gl}=useThree();configure(day,gl);configure(night,gl);configure(clouds,gl);useFrame((_,d)=>{body.current.rotation.y+=d*.02;cloud.current.rotation.y+=d*.031});return <group><mesh ref={body}><sphereGeometry args={[4,128,128]}/><meshStandardMaterial map={day} roughness={.35} metalness={.13}/></mesh><mesh scale={1.005}><sphereGeometry args={[4,96,96]}/><meshBasicMaterial map={night} transparent opacity={.22} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh><mesh ref={cloud} scale={1.02}><sphereGeometry args={[4,96,96]}/><meshBasicMaterial map={clouds} transparent opacity={.3} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh><Atmosphere radius={4} color="#68aaff" strength={.84}/></group>}

function OrbitingBody({distance,size,color,speed,phase=0,tilt=0}:{distance:number;size:number;color:string;speed:number;phase?:number;tilt?:number}){const orbit=useRef<THREE.Group>(null!);useFrame((_,delta)=>orbit.current.rotation.y+=delta*speed);return <group ref={orbit} rotation={[tilt,phase,0]}><mesh position={[distance,0,0]}><sphereGeometry args={[size,32,32]}/><meshStandardMaterial color={color} roughness={.88}/></mesh></group>}
function Jupiter(){return <group position={[58,0,0]}><Planet position={[0,0,0]} texture="/textures/planets/jupiter/jupiter-color-2k.jpg" size={7} atmosphere="#d7ad7c"/><OrbitingBody distance={9.1} size={.42} color="#d9a45f" speed={.19} phase={.2} tilt={.05}/><OrbitingBody distance={10.7} size={.38} color="#dce6e4" speed={.14} phase={1.8} tilt={-.04}/><OrbitingBody distance={12.6} size={.58} color="#9c8b72" speed={.1} phase={3.4} tilt={.03}/><OrbitingBody distance={14.2} size={.5} color="#5d554d" speed={.075} phase={5.1} tilt={-.06}/></group>}
function Saturn(){const [surface,ring]=useTexture(["/textures/planets/saturn/saturn-color-2k.jpg","/textures/planets/saturn/saturn-ring-2k.png"]);const {gl}=useThree();configure(surface,gl);configure(ring,gl,false);return <group position={[86,0,0]} rotation={[0,0,-.16]}><mesh><sphereGeometry args={[5.5,96,96]}/><meshStandardMaterial map={surface} roughness={.63}/></mesh><Atmosphere radius={5.5} color="#d6b987" strength={.42}/><group rotation={[1.05,.08,.36]}><mesh><ringGeometry args={[6.65,17.8,320]}/><meshBasicMaterial alphaMap={ring} color="#fff2cf" transparent opacity={1} alphaTest={.018} side={THREE.DoubleSide} depthWrite={false}/></mesh><mesh position={[0,0,-.035]}><ringGeometry args={[6.7,17.6,320]}/><meshBasicMaterial color="#c89f61" transparent opacity={.28} side={THREE.DoubleSide} depthWrite={false} blending={THREE.AdditiveBlending}/></mesh><mesh position={[0,0,.045]}><ringGeometry args={[8.15,15.9,320]}/><meshBasicMaterial alphaMap={ring} color="#ffffff" transparent opacity={.58} side={THREE.DoubleSide} depthWrite={false} blending={THREE.AdditiveBlending}/></mesh></group><OrbitingBody distance={20.5} size={.72} color="#c39a63" speed={.045} phase={2.1} tilt={.18}/><pointLight position={[-3,7,8]} color="#ffe0a0" intensity={4.5} distance={28}/></group>}
function Asteroids(){const items=useMemo(()=>Array.from({length:120},(_,i)=>({p:[29+(i%9)*1.2,Math.sin(i*7)*6,Math.cos(i*2.3)*6] as [number,number,number],s:.09+(i%4)*.07})),[]);return <group>{items.map((a,i)=><Float key={i} speed={.3} rotationIntensity={.8}><mesh position={a.p} scale={a.s}><dodecahedronGeometry args={[1,0]}/><meshStandardMaterial color="#4f4840" roughness={1}/></mesh></Float>)}</group>}
function Nebula(){const points=useMemo(()=>{const p=new Float32Array(2700);for(let i=0;i<p.length;i++)p[i]=(Math.random()-.5)*20;return p},[]);return <points position={[128,0,0]}><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial size={.11} color="#c66eff" transparent opacity={.55} blending={THREE.AdditiveBlending}/></points>}
const blackHoleVertex = `varying vec2 vUv; void main(){ vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }`;
const blackHoleFragment = `uniform float time; varying vec2 vUv; float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);} void main(){vec2 p=vUv-.5;float r=length(p)*2.;float a=atan(p.y,p.x);float flow=noise(vec2(a*7.-time*.42,r*18.+time*.18))+noise(vec2(a*19.+time*.7,r*6.));float inner=smoothstep(.22,.48,r);float outer=1.-smoothstep(.72,1.,r);float filaments=smoothstep(.35,.92,flow)*inner*outer;vec3 cool=vec3(.75,.035,.006);vec3 hot=vec3(1.,.43,.06);vec3 col=mix(cool,hot,smoothstep(.4,.9,flow))*filaments;col+=vec3(1.,.67,.27)*pow(1.-abs(r-.4)*7.,6.)*.7;gl_FragColor=vec4(col,filaments);}`;
function BlackHole(){const disk=useRef<THREE.Mesh>(null!),ring=useRef<THREE.Mesh>(null!);const material=useMemo(()=>new THREE.ShaderMaterial({vertexShader:blackHoleVertex,fragmentShader:blackHoleFragment,uniforms:{time:{value:0}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}),[]);useFrame((_,d)=>{disk.current.rotation.z+=d*.055;ring.current.rotation.z-=d*.1;material.uniforms.time.value+=d});return <group position={[150,0,0]} rotation={[.52,-.18,.12]}><mesh ref={disk} material={material} scale={[8.4,3.3,1]}><planeGeometry args={[2,2,128,128]}/></mesh><mesh><sphereGeometry args={[2.15,96,96]}/><meshBasicMaterial color="#000000"/></mesh><mesh ref={ring} scale={[1.06,1.06,1.06]}><torusGeometry args={[2.24,.075,20,160]}/><meshBasicMaterial color="#fff0bf" transparent opacity={.92} blending={THREE.AdditiveBlending}/></mesh><pointLight color="#ff572e" intensity={18} distance={18}/></group>}
function FinalScene(){const points=useMemo(()=>{const count=1800,data=new Float32Array(count*3);for(let i=0;i<count;i++){const j=i*3,r=5+Math.random()*24,a=Math.random()*Math.PI*2;data[j]=Math.cos(a)*r;data[j+1]=(Math.random()-.5)*4;data[j+2]=Math.sin(a)*r}return data},[]);return <group position={[176,0,-2]}><points><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial color="#d9e9ff" size={.075} transparent opacity={.62} depthWrite={false} blending={THREE.AdditiveBlending}/></points><mesh position={[14,0,-3]}><sphereGeometry args={[.7,48,48]}/><meshBasicMaterial color="#f4f7ff"/></mesh><pointLight position={[14,0,-3]} color="#c9dcff" intensity={11} distance={28}/><mesh position={[14,-2.1,-4]} rotation={[Math.PI/2,0,0]}><ringGeometry args={[5.5,11,160]}/><meshBasicMaterial color="#7898d0" transparent opacity={.12} side={THREE.DoubleSide} blending={THREE.AdditiveBlending}/></mesh></group>}
function World(){return <><color attach="background" args={["#03050b"]}/><ambientLight intensity={.12}/><hemisphereLight color="#9eb5d8" groundColor="#090b12" intensity={.18}/><directionalLight position={[-20,12,10]} intensity={3} color="#fff1d5"/><directionalLight position={[32,-8,24]} intensity={.48} color="#7894c4"/><Stars radius={220} depth={80} count={4500} factor={4} saturation={0} fade speed={.2}/><Earth/><Planet position={[12,0,0]} texture="/textures/planets/moon/moon-color-2k.jpg" size={1.7}/><Asteroids/><Planet position={[42,0,0]} texture="/textures/planets/mars/mars-color-2k.jpg" size={3.3} atmosphere="#c95f3f"/><Jupiter/><Saturn/><Nebula/><BlackHole/><FinalScene/><CameraRig/></>}
class TextureErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<Stars radius={120} depth={50} count={1200} factor={3}/>:this.props.children}}
export function ExperienceCanvas(){return <Canvas className="canvas" dpr={[1,1.25]} camera={{position:[0,0,12],fov:48}} gl={{antialias:true,toneMapping:THREE.ACESFilmicToneMapping,powerPreference:"high-performance"}}><TextureErrorBoundary><Suspense fallback={<Stars radius={120} depth={50} count={700} factor={2}/>}><World/></Suspense></TextureErrorBoundary></Canvas>}
