import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { Stars, useTexture } from "@react-three/drei";
import { Component, Suspense, useEffect, useLayoutEffect, useMemo, useRef, type ReactNode } from "react";
import * as THREE from "three";
import { useExperienceStore } from "../store/experienceStore";

type CameraPoint={position:[number,number,number];target:[number,number,number]};
const cameraPath:CameraPoint[]=[];
const chapterIndexes:number[]=[];
type OrbitRange={start:number;end:number;center:[number,number,number];radius:number;height:number};
const orbitRanges:OrbitRange[]=[];
const beginChapter=()=>chapterIndexes.push(cameraPath.length);
const addPoint=(position:[number,number,number],target:[number,number,number])=>cameraPath.push({position,target});
const addTravel=(position:[number,number,number],target:[number,number,number],steps=24)=>{const start=cameraPath[cameraPath.length-1];if(!start){addPoint(position,target);return}for(let step=1;step<=steps;step+=1){const mix=step/steps;addPoint([THREE.MathUtils.lerp(start.position[0],position[0],mix),THREE.MathUtils.lerp(start.position[1],position[1],mix),THREE.MathUtils.lerp(start.position[2],position[2],mix)],[THREE.MathUtils.lerp(start.target[0],target[0],mix),THREE.MathUtils.lerp(start.target[1],target[1],mix),THREE.MathUtils.lerp(start.target[2],target[2],mix)])}};
const vectorTuple=(vector:THREE.Vector3):[number,number,number]=>[vector.x,vector.y,vector.z];
const addSplineTravel=(waypoints:CameraPoint[],steps=110)=>{const start=cameraPath[cameraPath.length-1];if(!start){waypoints.forEach(point=>addPoint(point.position,point.target));return}const positionCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(...start.position),...waypoints.map(point=>new THREE.Vector3(...point.position))],false,"centripetal");const targetCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(...start.target),...waypoints.map(point=>new THREE.Vector3(...point.target))],false,"centripetal");for(let step=1;step<=steps;step+=1){const progress=step/steps;addPoint(vectorTuple(positionCurve.getPoint(progress)),vectorTuple(targetCurve.getPoint(progress)))}};
const addOrbit=(center:[number,number,number],radius:number,height:number,steps=72)=>{const start=cameraPath.length;for(let step=0;step<=steps;step+=1){const angle=(step/steps)*Math.PI*2;addPoint([center[0]+Math.sin(angle)*radius,height,center[2]+Math.cos(angle)*radius],center)}orbitRanges.push({start,end:cameraPath.length-1,center,radius,height})};
beginChapter();addOrbit([0,0,0],12,2);
beginChapter();addTravel([7,1,9],[12,0,0]);addTravel([12,1.5,6],[12,0,0]);addOrbit([12,0,0],6,1.5);
// Fly through the asteroid field's center with a restrained weave while keeping
// the camera aimed down the corridor toward Mars.
beginChapter();addSplineTravel([
 {position:[21,.8,2.6],target:[29,0,0]},
 {position:[27,-.8,.6],target:[35,.2,0]},
 {position:[33,.9,-.8],target:[40,0,0]},
 {position:[37,0,2.5],target:[42,0,0]},
]);
// Meet the Mars orbit at its exact opening position. The previous waypoint left
// the camera six units away from the orbit, forcing that distance into a single
// path step and producing a visible surge after the asteroid field.
beginChapter();addTravel([42,2.2,10],[42,0,0],36);addOrbit([42,0,0],10,2.2);
beginChapter();addTravel([48,2,18],[58,0,0]);addOrbit([58,0,0],18,4);
beginChapter();addTravel([72,4,25],[86,0,0]);addOrbit([86,0,0],24,6);
beginChapter();addTravel([105,0,11],[113,0,0]);addTravel([116,0,8],[123,0,0]);addTravel([121,0,6],[128,0,0]);
beginChapter();addTravel([124,0,9],[128,0,0]);addTravel([128,2,7],[128,0,0]);addTravel([135,-1,6],[142,0,0]);
beginChapter();addTravel([139,0,12],[150,0,0]);addTravel([146,2,10],[150,0,0]);addTravel([151,0,8],[150,0,0]);addTravel([157,-1,7],[150,0,0]);
beginChapter();addTravel([163,0,7],[172,0,0]);addTravel([172,0,5],[181,0,0]);addTravel([182,0,4],[191,0,0]);addTravel([192,0,3],[202,0,0]);
export const CHAPTER_CUES=chapterIndexes.map(index=>index/(cameraPath.length-1));
const ASTEROID_START=chapterIndexes[2];
const ASTEROID_END=chapterIndexes[3];
const MARS_END=chapterIndexes[4];
const asteroidLocalProgress=(scrollProgress:number)=>THREE.MathUtils.clamp((scrollProgress-CHAPTER_CUES[2])/(CHAPTER_CUES[3]-CHAPTER_CUES[2]),0,1);
const cameraPositions=cameraPath.map(point=>new THREE.Vector3(...point.position));
const cameraTargets=cameraPath.map(point=>new THREE.Vector3(...point.target));
function configure(texture: THREE.Texture, gl: THREE.WebGLRenderer, color=true) { useEffect(()=>{ if(color) texture.colorSpace=THREE.SRGBColorSpace; texture.anisotropy=gl.capabilities.getMaxAnisotropy(); texture.minFilter=THREE.LinearMipmapLinearFilter; texture.magFilter=THREE.LinearFilter; texture.needsUpdate=true },[texture,gl,color]) }

const atmosphereVertex="varying vec3 worldNormal;varying vec3 worldPosition;void main(){worldNormal=normalize(mat3(modelMatrix)*normal);worldPosition=(modelMatrix*vec4(position,1.0)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(worldPosition,1.0);}";
const atmosphereFragment="uniform vec3 glowColor;uniform float strength;varying vec3 worldNormal;varying vec3 worldPosition;void main(){vec3 viewDirection=normalize(cameraPosition-worldPosition);float rim=pow(1.0-max(dot(worldNormal,viewDirection),0.0),3.2);gl_FragColor=vec4(glowColor,rim*strength);}";
function Atmosphere({radius,color,strength=.72}:{radius:number;color:string;strength?:number}){return <mesh scale={1.035}><sphereGeometry args={[radius,56,56]}/><shaderMaterial vertexShader={atmosphereVertex} fragmentShader={atmosphereFragment} uniforms={{glowColor:{value:new THREE.Color(color)},strength:{value:strength}}} transparent depthWrite={false} side={THREE.BackSide} blending={THREE.AdditiveBlending}/></mesh>}
function CameraRig(){
 const renderedProgress=useRef(0),desiredPosition=useMemo(()=>new THREE.Vector3(),[]),desiredTarget=useMemo(()=>new THREE.Vector3(),[]);
 useFrame(({camera,clock},delta)=>{
  const {scrollProgress,reducedMotion,isPaused}=useExperienceStore.getState();
  if(isPaused)return;
  renderedProgress.current=reducedMotion?scrollProgress:THREE.MathUtils.damp(renderedProgress.current,scrollProgress,7,Math.min(delta,.05));
  const pathProgress=renderedProgress.current*(cameraPath.length-1),index=Math.min(Math.floor(pathProgress),cameraPath.length-2),mix=pathProgress-index,orbit=orbitRanges.find(range=>pathProgress>=range.start&&pathProgress<=range.end);
  if(orbit){const local=(pathProgress-orbit.start)/(orbit.end-orbit.start),angle=local*Math.PI*2;desiredPosition.set(orbit.center[0]+Math.sin(angle)*orbit.radius,orbit.height,orbit.center[2]+Math.cos(angle)*orbit.radius);desiredTarget.set(...orbit.center)}
  else{desiredPosition.lerpVectors(cameraPositions[index],cameraPositions[index+1],mix);desiredTarget.lerpVectors(cameraTargets[index],cameraTargets[index+1],mix);if(!reducedMotion)desiredPosition.y+=Math.sin(clock.elapsedTime*.2)*.08}
  camera.position.copy(desiredPosition);camera.lookAt(desiredTarget);
  if(camera instanceof THREE.PerspectiveCamera){const asteroidProgress=THREE.MathUtils.clamp((pathProgress-ASTEROID_START)/(ASTEROID_END-ASTEROID_START),0,1),lensBoost=reducedMotion?0:Math.pow(Math.sin(asteroidProgress*Math.PI),1.6)*6,targetFov=48+lensBoost;camera.fov=reducedMotion?targetFov:THREE.MathUtils.damp(camera.fov,targetFov,6,Math.min(delta,.05));camera.updateProjectionMatrix()}
 });
 return null;
}
type PlanetProps={position:[number,number,number];texture:string;size:number;atmosphere?:string};
function Planet({position,texture,size,atmosphere}:PlanetProps){const ref=useRef<THREE.Mesh>(null!);const map=useTexture(texture);const {gl}=useThree();configure(map,gl);useFrame((_,d)=>ref.current.rotation.y+=d*.025);return <group position={position}><mesh ref={ref}><sphereGeometry args={[size,80,80]}/><meshStandardMaterial map={map} roughness={.57} metalness={.04}/></mesh>{atmosphere&&<Atmosphere radius={size} color={atmosphere}/>}</group>}
function Earth(){const body=useRef<THREE.Mesh>(null!),cloud=useRef<THREE.Mesh>(null!);const [day,night,clouds]=useTexture(["/textures/planets/earth/earth-color-2k.jpg","/textures/planets/earth/earth-night-2k.jpg","/textures/planets/earth/earth-clouds-2k.jpg"]);const {gl}=useThree();configure(day,gl);configure(night,gl);configure(clouds,gl);useFrame((_,d)=>{body.current.rotation.y+=d*.02;cloud.current.rotation.y+=d*.031});return <group><mesh ref={body}><sphereGeometry args={[4,128,128]}/><meshStandardMaterial map={day} roughness={.35} metalness={.13}/></mesh><mesh scale={1.005}><sphereGeometry args={[4,96,96]}/><meshBasicMaterial map={night} transparent opacity={.22} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh><mesh ref={cloud} scale={1.02}><sphereGeometry args={[4,96,96]}/><meshBasicMaterial map={clouds} transparent opacity={.3} blending={THREE.AdditiveBlending} depthWrite={false}/></mesh><Atmosphere radius={4} color="#68aaff" strength={.84}/></group>}

function OrbitingBody({distance,size,color,speed,phase=0,tilt=0}:{distance:number;size:number;color:string;speed:number;phase?:number;tilt?:number}){const orbit=useRef<THREE.Group>(null!);useFrame((_,delta)=>orbit.current.rotation.y+=delta*speed);return <group ref={orbit} rotation={[tilt,phase,0]}><mesh position={[distance,0,0]}><sphereGeometry args={[size,32,32]}/><meshStandardMaterial color={color} roughness={.88}/></mesh></group>}
function Jupiter(){return <group position={[58,0,0]}><Planet position={[0,0,0]} texture="/textures/planets/jupiter/jupiter-color-2k.jpg" size={7} atmosphere="#d7ad7c"/><OrbitingBody distance={9.1} size={.42} color="#d9a45f" speed={.19} phase={.2} tilt={.05}/><OrbitingBody distance={10.7} size={.38} color="#dce6e4" speed={.14} phase={1.8} tilt={-.04}/><OrbitingBody distance={12.6} size={.58} color="#9c8b72" speed={.1} phase={3.4} tilt={.03}/><OrbitingBody distance={14.2} size={.5} color="#5d554d" speed={.075} phase={5.1} tilt={-.06}/></group>}
function Saturn(){const [surface,ring]=useTexture(["/textures/planets/saturn/saturn-color-2k.jpg","/textures/planets/saturn/saturn-ring-2k.png"]);const {gl}=useThree();configure(surface,gl);configure(ring,gl,false);return <group position={[86,0,0]} rotation={[0,0,-.16]}><mesh><sphereGeometry args={[5.5,96,96]}/><meshStandardMaterial map={surface} roughness={.63}/></mesh><Atmosphere radius={5.5} color="#d6b987" strength={.42}/><group rotation={[1.05,.08,.36]}><mesh><ringGeometry args={[6.65,17.8,320]}/><meshBasicMaterial alphaMap={ring} color="#fff2cf" transparent opacity={1} alphaTest={.018} side={THREE.DoubleSide} depthWrite={false}/></mesh><mesh position={[0,0,-.035]}><ringGeometry args={[6.7,17.6,320]}/><meshBasicMaterial color="#c89f61" transparent opacity={.28} side={THREE.DoubleSide} depthWrite={false} blending={THREE.AdditiveBlending}/></mesh><mesh position={[0,0,.045]}><ringGeometry args={[8.15,15.9,320]}/><meshBasicMaterial alphaMap={ring} color="#ffffff" transparent opacity={.58} side={THREE.DoubleSide} depthWrite={false} blending={THREE.AdditiveBlending}/></mesh></group><OrbitingBody distance={20.5} size={.72} color="#c39a63" speed={.045} phase={2.1} tilt={.18}/><pointLight position={[-3,7,8]} color="#ffe0a0" intensity={4.5} distance={28}/></group>}
const mulberry32=(seed:number)=>()=>{let value=seed+=0x6d2b79f5;value=Math.imul(value^value>>>15,value|1);value^=value+Math.imul(value^value>>>7,value|61);return((value^value>>>14)>>>0)/4294967296};
function createRockGeometry(seed:number,detail=1){const geometry=new THREE.DodecahedronGeometry(1,detail),positions=geometry.attributes.position,vertex=new THREE.Vector3();for(let index=0;index<positions.count;index+=1){vertex.fromBufferAttribute(positions,index);const noise=Math.sin(vertex.x*12.9898+vertex.y*78.233+vertex.z*37.719+seed*19.19)*43758.5453,radial=.78+(noise-Math.floor(noise))*.38;vertex.normalize().multiplyScalar(radial);positions.setXYZ(index,vertex.x,vertex.y,vertex.z)}positions.needsUpdate=true;geometry.computeVertexNormals();return geometry}
const asteroidCorridor:[[number,number,number],[number,number,number],[number,number,number],[number,number,number],[number,number,number]]=[[21,.8,2.6],[27,-.8,.6],[33,.9,-.8],[37,0,2.5],[42,2.2,10]];
function corridorAtX(x:number):[number,number]{for(let index=0;index<asteroidCorridor.length-1;index+=1){const start=asteroidCorridor[index],end=asteroidCorridor[index+1];if(x<=end[0]){const mix=THREE.MathUtils.clamp((x-start[0])/(end[0]-start[0]),0,1);return[THREE.MathUtils.lerp(start[1],end[1],mix),THREE.MathUtils.lerp(start[2],end[2],mix)]}}const last=asteroidCorridor[asteroidCorridor.length-1];return[last[1],last[2]]}
type RockInstance={position:THREE.Vector3;rotation:THREE.Euler;spin:THREE.Vector3;scale:THREE.Vector3;color:THREE.Color};
type AsteroidLayerProps={count:number;seed:number;minScale:number;maxScale:number;minDistance:number;maxDistance:number;color:string};
function AsteroidLayer({count,seed,minScale,maxScale,minDistance,maxDistance,color}:AsteroidLayerProps){
 const mesh=useRef<THREE.InstancedMesh>(null!),dummy=useMemo(()=>new THREE.Object3D(),[]),geometry=useMemo(()=>createRockGeometry(seed),[seed]),material=useMemo(()=>new THREE.MeshStandardMaterial({color,roughness:.94,metalness:.025,flatShading:true,vertexColors:true}),[color]);
 const items=useMemo<RockInstance[]>(()=>{const random=mulberry32(seed);return Array.from({length:count},()=>{const x=THREE.MathUtils.lerp(23,40.5,random()),[centerY,centerZ]=corridorAtX(x),angle=random()*Math.PI*2,distance=THREE.MathUtils.lerp(minDistance,maxDistance,Math.pow(random(),.72)),baseScale=THREE.MathUtils.lerp(minScale,maxScale,Math.pow(random(),1.6)),tint=new THREE.Color(color);tint.offsetHSL((random()-.5)*.035,(random()-.5)*.08,(random()-.5)*.12);return{position:new THREE.Vector3(x,centerY+Math.cos(angle)*distance,centerZ+Math.sin(angle)*distance),rotation:new THREE.Euler(random()*Math.PI,random()*Math.PI,random()*Math.PI),spin:new THREE.Vector3((random()-.5)*.24,(random()-.5)*.24,(random()-.5)*.24),scale:new THREE.Vector3(baseScale*(.7+random()*.55),baseScale*(.7+random()*.55),baseScale*(.7+random()*.55)),color:tint}})},[color,count,maxDistance,maxScale,minDistance,minScale,seed]);
 const writeMatrices=()=>{items.forEach((item,index)=>{dummy.position.copy(item.position);dummy.rotation.copy(item.rotation);dummy.scale.copy(item.scale);dummy.updateMatrix();mesh.current.setMatrixAt(index,dummy.matrix)});mesh.current.instanceMatrix.needsUpdate=true};
 useLayoutEffect(()=>{mesh.current.instanceMatrix.setUsage(THREE.DynamicDrawUsage);items.forEach((item,index)=>mesh.current.setColorAt(index,item.color));if(mesh.current.instanceColor)mesh.current.instanceColor.needsUpdate=true;writeMatrices();mesh.current.computeBoundingSphere()},[items]);
 useEffect(()=>()=>{geometry.dispose();material.dispose()},[geometry,material]);
 useFrame((_,delta)=>{const {isPaused,reducedMotion,scrollProgress}=useExperienceStore.getState();if(isPaused||reducedMotion||scrollProgress<CHAPTER_CUES[2]-.035||scrollProgress>CHAPTER_CUES[3]+.035)return;const step=Math.min(delta,.05);items.forEach(item=>{item.rotation.x+=item.spin.x*step;item.rotation.y+=item.spin.y*step;item.rotation.z+=item.spin.z*step});writeMatrices()});
 return <instancedMesh ref={mesh} args={[geometry,material,count]}/>;
}
type HeroRockProps={position:[number,number,number];scale:[number,number,number];rotation:[number,number,number];spin:[number,number,number];seed:number};
function HeroRock({position,scale,rotation,spin,seed}:HeroRockProps){const ref=useRef<THREE.Mesh>(null!),geometry=useMemo(()=>createRockGeometry(seed,2),[seed]);useEffect(()=>()=>geometry.dispose(),[geometry]);useFrame((_,delta)=>{const {isPaused,reducedMotion,scrollProgress}=useExperienceStore.getState();if(isPaused||reducedMotion||scrollProgress<CHAPTER_CUES[2]-.035||scrollProgress>CHAPTER_CUES[3]+.035)return;ref.current.rotation.x+=spin[0]*delta;ref.current.rotation.y+=spin[1]*delta;ref.current.rotation.z+=spin[2]*delta});return <mesh ref={ref} position={position} scale={scale} rotation={rotation} geometry={geometry}><meshStandardMaterial color="#62584d" roughness={.9} metalness={.035} flatShading/></mesh>}
function AsteroidDust({count}:{count:number}){const points=useMemo(()=>{const random=mulberry32(7319),data=new Float32Array(count*3);for(let index=0;index<count;index+=1){const offset=index*3,x=THREE.MathUtils.lerp(21,42,random()),[centerY,centerZ]=corridorAtX(x);data[offset]=x;data[offset+1]=centerY+(random()-.5)*9;data[offset+2]=centerZ+(random()-.5)*9}return data},[count]);return <points><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial color="#c7ac91" size={.032} transparent opacity={.42} depthWrite={false} blending={THREE.AdditiveBlending}/></points>}
function Asteroids(){const quality=useExperienceStore(state=>state.quality),counts={ultra:[260,140,50,620],high:[180,100,36,460],medium:[120,60,24,320],low:[70,32,12,180]}[quality];return <group><AsteroidLayer key={`far-${counts[0]}`} count={counts[0]} seed={1087} minScale={.055} maxScale={.2} minDistance={3.2} maxDistance={8} color="#504941"/><AsteroidLayer key={`mid-${counts[1]}`} count={counts[1]} seed={2903} minScale={.15} maxScale={.42} minDistance={1.9} maxDistance={5.5} color="#5b5147"/><AsteroidLayer key={`near-${counts[2]}`} count={counts[2]} seed={4517} minScale={.3} maxScale={.72} minDistance={1.45} maxDistance={3.2} color="#665a4d"/><HeroRock position={[27.8,2.25,.2]} scale={[1.15,.82,1]} rotation={[.4,.8,.1]} spin={[.08,-.13,.04]} seed={11}/><HeroRock position={[31.2,-1.75,-2.2]} scale={[1.2,1.05,.86]} rotation={[1.1,.2,.7]} spin={[-.1,.06,.12]} seed={23}/><HeroRock position={[34.7,2.35,1.05]} scale={[1.05,1.25,.92]} rotation={[.3,1.4,.2]} spin={[.05,.11,-.08]} seed={37}/><HeroRock position={[38.1,-1.7,4.5]} scale={[1.28,.88,1.04]} rotation={[.9,.4,1.2]} spin={[-.06,.12,.07]} seed={53}/><AsteroidDust count={counts[3]}/></group>}
function MarsApproachLight(){const ref=useRef<THREE.PointLight>(null!);useFrame((_,delta)=>{const {scrollProgress,reducedMotion,isPaused}=useExperienceStore.getState();if(isPaused)return;const pathProgress=scrollProgress*(cameraPath.length-1),fadeIn=THREE.MathUtils.smoothstep(pathProgress,ASTEROID_START+(ASTEROID_END-ASTEROID_START)*.48,ASTEROID_END),fadeOut=1-THREE.MathUtils.smoothstep(pathProgress,MARS_END-18,MARS_END),targetIntensity=9*fadeIn*fadeOut;ref.current.intensity=reducedMotion?targetIntensity:THREE.MathUtils.damp(ref.current.intensity,targetIntensity,5,Math.min(delta,.05))});return <pointLight ref={ref} position={[40,1.5,3.5]} color="#e86e43" intensity={0} distance={20} decay={1.7}/>}
function Nebula(){const points=useMemo(()=>{const p=new Float32Array(2700);for(let i=0;i<p.length;i++)p[i]=(Math.random()-.5)*20;return p},[]);return <points position={[128,0,0]}><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial size={.11} color="#c66eff" transparent opacity={.55} blending={THREE.AdditiveBlending}/></points>}
const blackHoleVertex = `varying vec2 vUv; void main(){ vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0); }`;
const blackHoleFragment = `uniform float time; varying vec2 vUv; float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);} float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.0-2.0*f);return mix(mix(hash(i),hash(i+vec2(1.,0.)),f.x),mix(hash(i+vec2(0.,1.)),hash(i+vec2(1.,1.)),f.x),f.y);} void main(){vec2 p=vUv-.5;float r=length(p)*2.;float a=atan(p.y,p.x);float flow=noise(vec2(a*7.-time*.42,r*18.+time*.18))+noise(vec2(a*19.+time*.7,r*6.));float inner=smoothstep(.22,.48,r);float outer=1.-smoothstep(.72,1.,r);float filaments=smoothstep(.35,.92,flow)*inner*outer;vec3 cool=vec3(.75,.035,.006);vec3 hot=vec3(1.,.43,.06);vec3 col=mix(cool,hot,smoothstep(.4,.9,flow))*filaments;col+=vec3(1.,.67,.27)*pow(1.-abs(r-.4)*7.,6.)*.7;gl_FragColor=vec4(col,filaments);}`;
function BlackHole(){const disk=useRef<THREE.Mesh>(null!),ring=useRef<THREE.Mesh>(null!);const material=useMemo(()=>new THREE.ShaderMaterial({vertexShader:blackHoleVertex,fragmentShader:blackHoleFragment,uniforms:{time:{value:0}},transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,side:THREE.DoubleSide}),[]);useFrame((_,d)=>{disk.current.rotation.z+=d*.055;ring.current.rotation.z-=d*.1;material.uniforms.time.value+=d});return <group position={[150,0,0]} rotation={[.52,-.18,.12]}><mesh ref={disk} material={material} scale={[8.4,3.3,1]}><planeGeometry args={[2,2,128,128]}/></mesh><mesh><sphereGeometry args={[2.15,96,96]}/><meshBasicMaterial color="#000000"/></mesh><mesh ref={ring} scale={[1.06,1.06,1.06]}><torusGeometry args={[2.24,.075,20,160]}/><meshBasicMaterial color="#fff0bf" transparent opacity={.92} blending={THREE.AdditiveBlending}/></mesh><pointLight color="#ff572e" intensity={18} distance={18}/></group>}
function FinalScene(){const points=useMemo(()=>{const count=1800,data=new Float32Array(count*3);for(let i=0;i<count;i++){const j=i*3,r=5+Math.random()*24,a=Math.random()*Math.PI*2;data[j]=Math.cos(a)*r;data[j+1]=(Math.random()-.5)*4;data[j+2]=Math.sin(a)*r}return data},[]);return <group position={[176,0,-2]}><points><bufferGeometry><bufferAttribute attach="attributes-position" args={[points,3]}/></bufferGeometry><pointsMaterial color="#d9e9ff" size={.075} transparent opacity={.62} depthWrite={false} blending={THREE.AdditiveBlending}/></points><mesh position={[14,0,-3]}><sphereGeometry args={[.7,48,48]}/><meshBasicMaterial color="#f4f7ff"/></mesh><pointLight position={[14,0,-3]} color="#c9dcff" intensity={11} distance={28}/><mesh position={[14,-2.1,-4]} rotation={[Math.PI/2,0,0]}><ringGeometry args={[5.5,11,160]}/><meshBasicMaterial color="#7898d0" transparent opacity={.12} side={THREE.DoubleSide} blending={THREE.AdditiveBlending}/></mesh></group>}
function SceneWarmup(){const {gl,scene,camera}=useThree();useEffect(()=>{let cancelled=false;const warm=()=>{if(cancelled)return;const textures=new Set<THREE.Texture>();scene.traverse(object=>{if(!("material" in object))return;const candidate=object as THREE.Object3D&{material?:THREE.Material|THREE.Material[]},materials=Array.isArray(candidate.material)?candidate.material:candidate.material?[candidate.material]:[];materials.forEach(material=>Object.values(material).forEach(value=>{if(value instanceof THREE.Texture)textures.add(value)}))});textures.forEach(texture=>gl.initTexture(texture));void gl.compileAsync(scene,camera).catch(()=>undefined)};const browser=window as typeof window&{requestIdleCallback?:(callback:()=>void,options?:{timeout:number})=>number;cancelIdleCallback?:(id:number)=>void};if(browser.requestIdleCallback){const id=browser.requestIdleCallback(warm,{timeout:1200});return()=>{cancelled=true;browser.cancelIdleCallback?.(id)}}const id=window.setTimeout(warm,180);return()=>{cancelled=true;clearTimeout(id)}},[camera,gl,scene]);return null}
function World(){return <><color attach="background" args={["#03050b"]}/><ambientLight intensity={.12}/><hemisphereLight color="#9eb5d8" groundColor="#090b12" intensity={.18}/><directionalLight position={[-20,12,10]} intensity={3} color="#fff1d5"/><directionalLight position={[32,-8,24]} intensity={.48} color="#7894c4"/><MarsApproachLight/><Stars radius={220} depth={80} count={4500} factor={4} saturation={0} fade speed={.2}/><Earth/><Planet position={[12,0,0]} texture="/textures/planets/moon/moon-color-2k.jpg" size={1.7}/><Asteroids/><Planet position={[42,0,0]} texture="/textures/planets/mars/mars-color-2k.jpg" size={3.3} atmosphere="#c95f3f"/><Jupiter/><Saturn/><Nebula/><BlackHole/><FinalScene/><CameraRig/><SceneWarmup/></>}
class TextureErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<Stars radius={120} depth={50} count={1200} factor={3}/>:this.props.children}}
function playAsteroidWhoosh(context:AudioContext){const duration=.9,frameCount=Math.floor(context.sampleRate*duration),buffer=context.createBuffer(1,frameCount,context.sampleRate),data=buffer.getChannelData(0),random=mulberry32(9321);for(let index=0;index<frameCount;index+=1){const progress=index/frameCount;data[index]=(random()*2-1)*Math.sin(progress*Math.PI)}const now=context.currentTime,source=context.createBufferSource(),filter=context.createBiquadFilter(),panner=context.createStereoPanner(),gain=context.createGain();source.buffer=buffer;filter.type="bandpass";filter.Q.value=.7;filter.frequency.setValueAtTime(180,now);filter.frequency.exponentialRampToValueAtTime(1450,now+.34);filter.frequency.exponentialRampToValueAtTime(240,now+duration);panner.pan.setValueAtTime(-.65,now);panner.pan.linearRampToValueAtTime(.7,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.22,now+.24);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);source.connect(filter).connect(panner).connect(gain).connect(context.destination);source.start(now);source.stop(now+duration)}
function AsteroidSound(){const soundEnabled=useExperienceStore(state=>state.soundEnabled);useEffect(()=>{if(!soundEnabled)return;const context=new AudioContext();void context.resume();let lastProgress=asteroidLocalProgress(useExperienceStore.getState().scrollProgress);const unsubscribe=useExperienceStore.subscribe(state=>{const progress=asteroidLocalProgress(state.scrollProgress);if(!state.isPaused&&lastProgress<.62&&progress>=.62&&progress<.98)playAsteroidWhoosh(context);lastProgress=progress});return()=>{unsubscribe();void context.close()}},[soundEnabled]);return null}
export function ExperienceCanvas(){return <><AsteroidSound/><Canvas className="canvas" dpr={[1,1.25]} camera={{position:[0,0,12],fov:48}} gl={{antialias:true,toneMapping:THREE.ACESFilmicToneMapping,powerPreference:"high-performance"}}><TextureErrorBoundary><Suspense fallback={<Stars radius={120} depth={50} count={700} factor={2}/>}><World/></Suspense></TextureErrorBoundary></Canvas></>}
